`ifndef ALIGNER_TEST_DEFINES_SV
  `define ALIGNER_TEST_DEFINES_SV

  `ifndef ALIGNER_DATA_WIDTH
    `define ALIGNER_DATA_WIDTH 32
  `endif // ALIGNER_DATA_WIDTH

`endif // ALIGNER_TEST_DEFINES_SV